// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuayIntegration) DeepCopyInto(out *QuayIntegration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuayIntegration.
func (in *QuayIntegration) DeepCopy() *QuayIntegration {
	if in == nil {
		return nil
	}
	out := new(QuayIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuayIntegration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuayIntegrationList) DeepCopyInto(out *QuayIntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuayIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuayIntegrationList.
func (in *QuayIntegrationList) DeepCopy() *QuayIntegrationList {
	if in == nil {
		return nil
	}
	out := new(QuayIntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuayIntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuayIntegrationSpec) DeepCopyInto(out *QuayIntegrationSpec) {
	*out = *in
	if in.BlacklistNamespaces != nil {
		in, out := &in.BlacklistNamespaces, &out.BlacklistNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WhitelistNamespaces != nil {
		in, out := &in.WhitelistNamespaces, &out.WhitelistNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuayIntegrationSpec.
func (in *QuayIntegrationSpec) DeepCopy() *QuayIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(QuayIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuayIntegrationStatus) DeepCopyInto(out *QuayIntegrationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuayIntegrationStatus.
func (in *QuayIntegrationStatus) DeepCopy() *QuayIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(QuayIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}
