apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: quay-bridge-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    name: quay-bridge-operator
status:
  loadBalancer: {}
