
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /admissionwebhook
  failurePolicy: Fail
  name: quayintegration.quay.redhat.com
  rules:
  - apiGroups:
    - build.openshift.io
    apiVersions:
    - v1
    operations:
    - '*'
    resources:
    - builds
  sideEffects: None
