# permissions for end users to view quayintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quayintegration-viewer-role
rules:
- apiGroups:
  - quay.redhat.com
  resources:
  - quayintegrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quay.redhat.com
  resources:
  - quayintegrations/status
  verbs:
  - get
