# permissions for end users to edit quayintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quayintegration-editor-role
rules:
- apiGroups:
  - quay.redhat.com
  resources:
  - quayintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quay.redhat.com
  resources:
  - quayintegrations/status
  verbs:
  - get
