apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: quay-bridge-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  - serviceaccounts
  - namespaces
  # Need to remove pods or separate out into a basic role
  - pods
  - configmaps
  verbs:
  - 'create'
  - 'update'
  - 'get'
  - 'list'
  - 'watch'
  - 'delete'
  - 'patch'
  - 'put'
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamimports
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - build.openshift.io
  resources:
  - builds
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - '*'
  - quayintegrations 
  verbs:
  - '*'

