kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quay-bridge-operator
subjects:
- kind: ServiceAccount
  name: quay-bridge-operator
  # Update This value with the namesapce the operator will be deployed within
  namespace: quay-bridge-operator
roleRef:
  kind: ClusterRole
  name: quay-bridge-operator
  apiGroup: rbac.authorization.k8s.io