apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: quay-bridge-operator.v1.0.0
  namespace: placeholder
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "redhatcop.redhat.io/v1alpha1",
          "kind": "QuayIntegration",
          "metadata": {
            "name": "my-quay"
          },
          "spec": {
            "clusterID": "openshift",
            "credentialsSecretName": "<NAMESPACE>/<SECRET>",
            "quayHostname": "https://<QUAY_URL>",
            "insecureRegistry": false,
            "whitelistNamespaces": ["default"]
          }
        }
      ]
    capabilities: Full Lifecycle
    categories: ""
    containerImage:
    createdAt: 2020-3-18 01:03:00
    description: Enhance OCP using Red Hat Quay container registry
    repository: https://github.com/redhat-cop/quay-openshift-registry-operator
    tectonic-visibility: ocs
spec:
  description: |-
    ## Overview

    The OpenShift Container Platform contains an in cluster image registry for pushing and pulling images that either produced within the cluster or are references from external sources. Quay is a highly available, enterprise grade image registry with enhanced role based access control (RBAC) features. The goal of this operator is to support replicating the features found within OpenShift intgrated image registry with Quay.

    ## Functionality

    The following capabilities are enabled through this operator:

    * Synchronization of OpenShift namespaces as Quay organizations
        * Creation of Robot accounts for each default namespace service account
        * Creation of Secrets for each created Robot Account
            * Associate Robot Secret to Service Account as Mountable and Image Pull Secret
        * Synchronization of OpenShift ImageStreams as Quay Repositories
    * Automatically rewrite new Builds making use of ImageStreams to output to Quay
    * Automatically import ImageStream tag once build completes

    ## Prerequisites

    The following requirements must be satisfied prior to setting and configuring the integration between OpenShift and Quay:

    * A Red Hat Quay environment with a user with superuser permissions
    * A Red Hat OpenShift Container Platform environment (at least version 3.6 [3.11 recommended]) with cluster-admin permissions on an OpenShift cluster 
    *	OpenShift Command Line tool (CLI)

    ## Setup and Configuration

    The setup process involves steps within both Quay and OpenShift as described below:

    ### Quay Setup

    The integration between OpenShift and Quay makes extensive use of the Quay RESTFul API. To allow for other methods aside from user credentials to be used for authenticating against the API, an application is required to be created. When an application is created, an OAuth token is generated which can be used by the operator in OpenShift. Applications are created within a Quay organization. While an existing organization can be utilized, it is recommended that a dedicated organization be used.

    1.	Login to Quay as a user with superuser access and select the organization for which the external application will be configured within.
    2.	On the left hand side of the page, select **Applications**
    3.	Create a new application by selecting the **Create New Application** button and entering a name for the application
    4.	After the new application has been created, select the application that was created
    5.	On the lefthand navigation bar, select the **Generate Token** button to create a new OAuth2 token
    6.	Select all of the checkboxes to grant the necessary access that is needed for the integration
    7.	Review the permissions that will be assigned and then select the **Authorize Application** button
    8.	Take note of the generated Access Token as it will be needed in the following section

    ### OpenShift Setup

    To complete the process to begin to integrate OpenShift and Quay, several steps are required. Before beginning, ensure that you have the OpenShift Command Line tool installed and that you are logged into OpenShift as a cluster administrator. 

    #### Create A Secret for the Quay OAuth Token

    The Operator will use the previously obtained Access Token to communicate with Quay. Store this token within OpenShift as a secret.

    Execute the following command to create a secret called `quay-integration` with a key called `token` containing the access token:

    ```
    $ oc create secret generic quay-integration --from-literal=token=<access_token>
    ```

    This token will be referenced in the following section.


    #### Create the QuayIntegration Custom Resource

    Finally, to complete the integration between OpenShift and Quay, a `QuayIntegration` custom resource needs to be created.

    The following is an example of a basic definition of a `QuayIntegration` resource associated from the associated CRD.

    ```
    apiVersion: redhatcop.redhat.io/v1alpha1
    kind: QuayIntegration
    metadata:
      name: example-quayintegration
    spec:
      clusterID: openshift
      credentialsSecretName: <NAMESPACE>/<SECRET>
      quayHostname: https://<QUAY_URL>
    ```

    The _clusterID_ is a value which should be unique across the entire ecosystem. This value is optional and defaults to `openshift`.

    The _credentialsSecretName_ is a NamespacedName value of the secret containing the token that was previously created.

    Note: If Quay is using self signed certificates, the property `insecureRegistry: true`

    Organizations within Quay should be created for the related namespaces in OpenShift.
  displayName: Quay Bridge Operator
  install:
    spec:
      deployments:
      - name: quay-bridge-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: quay-bridge-operator
          template:
            metadata:
              labels:
                name: quay-bridge-operator
            spec:
              serviceAccountName: quay-bridge-operator
              containers:
                - name: quay-bridge-operator
                  image: quay.io/quay/quay-bridge-operator@sha256:029fd7a5e09e3f564826257dce39cba76e3e1589d8b8ee0dff828699a5e0abef
                  imagePullPolicy: Always
                  env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: "quay-bridge-operator"
                    - name: DISABLE_WEBHOOK
                      value: "true"
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - events
          - serviceaccounts
          - namespaces
          - pods
          - configmaps
          verbs:
          - create
          - update
          - get
          - list
          - watch
          - delete
          - patch
          - put
        - apiGroups:
          - ""
          - image.openshift.io
          resources:
          - imagestreams
          - imagestreamimports
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - builds
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - redhatcop.redhat.io
          resources:
          - '*'
          - quayintegrations 
          verbs:
          - '*'
        serviceAccountName:  quay-bridge-operator
    strategy: deployment
  installModes:
  - supported: True
    type: OwnNamespace
  - supported: False
    type: SingleNamespace
  - supported: False
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - registry
  - containers
  - quay
  labels:
    alm-owner-quay-bridge-operator: quay-bridge-operator
    operated-by: quay-bridge-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAACXBIWXMAAAsSAAALEgHS3X78AAANmElEQVR4nO2dfWxWVx3Hv/d5aWkpbYE5ZNA+DSB03WAlQx1IhIQxTJyhSzY1SrI5tsQ/TISoMcaYsfiHLnGuJv6xhDFYYkx8iStRk7mOMBKkqEzKNmrBsfVpgYmOrm/07Xm55vf0nHJ7z733Oefcc9tC+0mawj2X9nmeL9/fOef3O+dcy7ZtzGY6U9Z2AI0A6tj3agD3Sb7kcwD6ALQD6KLv9Wn7TeGuWcSsEqQzZdGHvd3xJfvBq0JCvcm/6tN2X3TvSo0ZF4SJ0MS+dgs3TA9HAbTQ10yLM2OCsFD0BIDHhcaZ5RUAR2YqtE27IJ0pi0TYF2E4MgWFteb6tH1kOn/ptAnChDgAICU0zm7S9LqnS5jIBWGhiYTYJjTeWpxgwkQayiIThHXWzbOwjwgL9TH7our8IxGkM2XRiIksXiU03h7004CkPm23mH43RgVhrqDw9G2h8fbkFyyMGXOLMUE6U1YdG8vP9tGTaWg01lSftrtM/NyYcEUD1nG3z0ExwN5zO/sMQhNaEDacPX4b9xcy0Hs/zj6LUIQShL2Aw0LD3OVwWFG0BZkXw5fD/6yxfurXWAytTn1eDH8Gc8CoDSyI4dCne+ynfG/0Qdkh82L4w8UgRvPY+48a6yXfm31QcggbSRwXGuaZIoaTshj2b+qxm4UGH6QFYfOMdhOjqXhlNVaf6kJskfyPGhkZQfuLL2Bx8w+FtiCWP38EVY+qZW/+/qejqPje1xEbviG0eeEnBmEBdlkMn7+/xz4pNHogFbLYDLzF1NC2YleTkhiF19B2EoN165AvXyi0+UHCL9rV5NPqTW9vL3oTpRhu3OLZ7iZIDMIGrDEbr79VY0lluWX7kAMmJ3137D8gXAuC3HFtPId82UIM7Hgk4M6pLN67T0t4ou/hPUKbm2JicHI2yrI2pPJeRQVhiUJjuamqx55AcoVaSaT7X+cn/zywo0nKJeSOJXv3CdeDIOEH4iWFO7JL78TQlp2+d8uKwRm30XimxvqJ0OAiUBAWqowWZlTdkclk0H31w8m/y7okjDs4fi5RFYMzmsf3i4WuQEFYPcNYSoTiuao73n/nHHKJ5JRr5JJi6LiDwqITcslw4+Yp13TFAOtPsjaOCQ0OfAVhQ1yjxaXFT6p9SG53cMglQeGEwmJYd3CcbgwjBmfcxuozNZbvB+ErCOvIjVH+wHaUP6BWxe3peFdwB8cvnEAzLLrdwRldux6jazcYEWPy99l4RrjI8BSEzcaN1sBVPySiq7tbuMbx63R1Bg0UFoO4/vAeY2IQWRvVfrN4T0FmgzsuX3oP48lS4boTL5eEHTR4kVm3Hrl1Gzxa9BnPe3cHgiDMHUaX6tD/WlUudpwv+i/cna6pQYMX2a2iG8OQBxJeLhEEYYvYjJFcWaecupBxB8fZ6ZoaNHiR3fIg7DuWebTok7HxNfc/niIIG1kZLcPq9B3dnR3CNT94p6sTFq91p6XcwRnfLYbIMNAM3j3icjskdAnSiY47BgYGJmfLsvR9aY+W8DJh0UkULsnZ+Jbz75OCsFm50XmHzoeUaW1BbEQuy8ohl6i6Iz/Yj9JzfxOuF8O0S2he4py9Ox2ilhYtgk6mlej7+TOoPKa2/qwyNy5cK0bvoWZU/eHlIneJ5DZuhq2QcZYhD/yI3xaZIDq5pP7fv4LM5S5UHntVySX1m7cK14Igd3x8qBmJ69dQ0fZGwJ0idtlCZHbKZ5xlyNn4Ir+tIAgLV8Y2y+hkWon+303kMakwVN7eJrR7Qe5YsmSJR4s/g39pQW5gYrFh7GSr731+ZHc2GXVJxsYnedjiDjGyyIuj447h0ycwfPrmwvLqP/5KuMcLVXcQH70w0bdROiTX+TbiF94R7gkiCpfYwDcRlSA6E0H+IXFkwkl5ZkzZHTwsOnNTyaNy4jvJfs7sRDFn4wuIQhCdXJLbHZxiLlnVcI9wrRgkvDtRGL+g4ZKldxoVJQesg0OQGSvPEh+/7L0og1xSfs67LynJjGHl6jXC9SCGXj+K3nSXZ6Iw2fqqcK0YJofANEmk7zFTi4Sh6Y7MlXShk/Wj8g3vtrUa7rh8sNlTDCJ+tg3W9f8K14Mw7RKatcfYZnwj6LjD3Xe4WXDxbSy4ODWc6Lhj8PQJ/O+UGBan/FyNvsSkS2wb22LshITQUC5Jxx18qBuEuy+pq60NuNubD34WLDyR+GurlktMpebzQJ0xh0ThDo7TJfFsBjUN9wr3BNHfdgL9bcHu4Oi4JGPIJVyQaqFFEZ1MK82WhwL6DjcVbRMTuNq7liOZlM/QEtd+K79wJn72FCzFXFrOUAHLBkpjJkZYOu6gXBKfLctQcaoVZYN9WLVe7eWOXU4rCWIN30CiVX0vpwmX0EjLq0ClxIKGRi13UC5JlU0N65TdkX5e/T8LDYF1XJKvXSVcVyW0IIs1claq7gALiwvv2ShcD0LVHRxtlxhIp4QSRKcARei4Qycs6riDozNRNFHACiWIzodEuSQdd6iGxexgP66/pr+vv+CSU8G5NC/CzkuMbIuexxyhBJGdRzihEEf1EhUo8UgJSBUSi6qw7Cv6SwSo3kEhSBWdeYyTUIJQGptCkCo6AwEd8Vc8pb+iSaeDphBnfXRNuK5C6JCl80FRNVHHJTfOnxWuB1G6MoVlX1Z3ScEdO9Ur2mHdAROCkEtUwwlVE3VccqbjQmFxmwqp72isfNn5SKEqqALVU8K6A0yQ4JXGEkyHS2hh9cii6qILo92oukTXHTpVRzdxCyMxdq5tKHQ6XXJJhcIyoaHNE3WH9NUPlV2iIkhu4xYtd1DVMSwWMBZjW51Do+MS2XkMLRWlxXBEPpFEuuNd4Z4gqjZvQ9VmuTqczjzChDswEa66YuzE59CQS6i+ofRGVqSkFkRcd207SHepv2SZvoSqf1TfUIHqJybcAYcgRhyCiFzSu2ZDYX+Gk0xpGbovvSfcG4SMS3TcYWJkxbEsnIiZPGWTqn8mXUKrQ2486N3P/FtxoTSx4mn/kZ2uO6jKaAo6goMPe0OPtDh6s3dREBJjZOmywlpaLzLJUmWXLN21GwtqvCvWOosVTLqDRlhwzENm1CWUOKQEIoevmyoWQt7XcEmtR19C1b6cKywWw7Q74sAFRCEIHGt0VeB9CReD0tjFckmjydLC2SQqLHvsccElOtU+k2JgwiGvISpBqN5BVUEVCun1z2yfXDcl28F2+OwvD8LpEi13jNzQqpcEYQEvggvCzp09GnC/ElTv6NUoQi1mEziaLfv1HW6G4iVaLkmwLIHOZk6qJlqSRzfJkLTwn/t77EKcd+ayjJ7SrOMSHk5Uc0k6LqERl0xYdBOFO+IW/sz/HJkg5BKdvmTFd59VziUNKe5JJO56eh+yjz4pXC9GYTGdQXdgQoQfO/48AQtb6sWNAHTCVsVDTVq5JFoMpwIVsOzGzyq/vqTG4ocgSixc4uEKHul3o0cx6RSwKisrUaG4Z5BySToLGj6luGDbRAHKTdzCL52XpgjCZu3GJonQnCjW1jcI1/zgmVZaKqrqkuW1KcSy8pljkxNBsMmg+4BMrwKVepwJQMcltavXIJkZE6574exgr7yk9tJp0R0tTZUhCnckLfzafU0QhD3aR22qXQSdzl0mnBQyrWdvbuihZT+0OE6F1evvk3JJQmNzaBAxIOt10LIgCMPoaUCUmh9ULGDJuMQrhKj2JTIuMVWAclIS8x5AeQrCXKL2CQZA6RCZ/RluUgH7QPxySbR0VMclQZgqQHESFvq83AE/QRhGXMJzUzqdbqrhXt9w4uUOjo5LPlESF64jInckLTwrXGT4CsJGXJ62ksW929VUp0uzZS93cMglWcUsQYPPfnfTs3KadwQdPe4rCGMfewCWMl5nFJrqdGVWpl896PuePSkrKxNc4h40hIWOHU9Y2BH0YwIFYbN3sXpUBC8xOGE7Xdlc0pWDzaFdEhQWdVgQw3POWbkXgYJgQpQW9jQyKYLEgGanm7r75hBYNtOaHejTcgnPEvgNGnQpsdC+qcf+QbF/rnL2e9EZvOxRqqou4eFENdMaxiWmy7MJS+60JSlBWOhqCupPVM61pb5E54Mq/eCCUqaVXKK6R4TOTqnKjhU2f5qA+o1SCw8VC1UcIw90MXnI8O1GWQxf3dRj/0b2bSkttmZD4W84r82L4Q89h0pFDOisfmez+IIo82L4M20PBQMTZTiP5+bF8EZXDIR9Fi6dzExPIxMa5jBhxEDYDTv0i+kFCA1zlLBiwMQOKnoB9Gg4q3BUx9yEPYltf1gxYPLx3W/VWFvpaWT8ZLS5Ak362DxDfS2SB8b2qdMLKrVwN6UIhMbbFHqv9J5NiQGTDnFCTyOjB2DZBTffflCIokShTG5KlUgEwUQIS9EDsOhsc6HxFobqGZRCl02FqBKZIBw62JGeuUSP+REabyGo7EqVvqDikgkiF4RDcxZ6zA89WUZonMXQ6hBakGBiBCXDtAnCIWHoyTKzfTRGoydaNzVdQnCmXRAOhTJ6mMls62Ooj6DlnVGHJj9mTBAOdf70/Ax6ZAM9JUC4YRqg/Rm0JYBWoUfVWcsy44I4IXHoKQF0MD2dhR5VWKNwRHv6aBsZ7VyaaRGczCpBvKDQRic+05m29EVHqcoKRR88O66CNuR30T7wmQpFUgD4Px6QRGRh7pGzAAAAAElFTkSuQmCC
    mediatype: image/png
  maturity: alpha
  links:
  - name: Source Code
    url: https://github.com/redhat-cop/quay-openshift-registry-operator
  maintainers:
  - email: quay-devel@redhat.com
    name: Quay Engineering Team
  provider:
    name: Red Hat
  selector:
    matchLabels:
      alm-owner-quay-bridge-operator: quay-bridge-operator
      operated-by: quay-bridge-operator
  version: 1.0.0
  customresourcedefinitions:
    owned:
    - description: Represents a connected Quay instance.
      displayName: Quay Integration
      kind: QuayIntegration
      name: quayintegrations.redhatcop.redhat.io
      version: v1alpha1
      specDescriptors:
      - description: List of namespaces that will not be enabled
        displayName: Blacklisted Namespaces
        path: blacklistNamespaces
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:blacklistNamespaces'
        - 'urn:alm:descriptor:com.tectonic.ui:string'
      - description: List of namespaces that will be enabled
        displayName: Whitelisted Namespaces
        path: whitelistNamespaces
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:arrayFieldGroup:whitelistNamespaces'
        - 'urn:alm:descriptor:com.tectonic.ui:string'
